# Generated by Django 5.0.1 on 2025-11-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
